# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='friended',
            field=models.ManyToManyField(related_name='_user_friended_+', to='loginreg_app.User'),
        ),
    ]
